name: Hello world
on: push 
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: greeting statement
        run: |
          echo "hi $"{{vars.MY_NAME}}" "
          echo "welcome to git hub actions "
          echo " echo"{{secrets.DOCKER_PASSWORD}}""
  
  build: 
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: build step 
        run: echo " this is demo build "
  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: test
        run: echo " this is demo test "
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: test
        run: echo " this is test "
