name: build and deploy
on: 
    pull_request:
        types:
            - opened
            - synchronize
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: echo " builduing the application"